version: '3.7'

services:

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - db_password
    ports:
      - "5432:5432"

  backend:
    image: backend
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - DEBUG=True
    restart: on-failure
    ports:
      - 8000:8000
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/static:/static
    command: >
      sh -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    secrets:
      - db_password

  frontend:
    image: frontend
    env_file:
      - .env
    ports:
      - 4200:4200
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0
    depends_on:
      - backend

secrets:
  db_password:
    file: db_password.txt

volumes:
  postgres_data:
  static:

