version: '3.7'

services:

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
       - db_password
    ports:
      - "5432:5432"

  backend:
    image: backend
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - SECRET_KEY=/run/secrets/secret_key
      - DEBUG=False
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    volumes:
      - ./backend:/app
      - static:/static
    command: >
      sh -c "python manage.py makemigrations
      && python manage.py migrate
      && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - database
    secrets:
      - db_password

  nginx-backend:
    image: nginx
    build:
      context: ./backend/nginx
    ports:
      - 8000:80
    volumes:
      - static:/static
    depends_on:
      - backend

  frontend:
    image: frontend
    env_file:
      - .env
    ports:
      - 4200:4200
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    depends_on:
      - database
      - backend
      - nginx-backend

secrets:
  db_password:
    file: db_password.txt

volumes:
  postgres_data:
  static: